/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sfc.sf2.portrait.gui;

import com.sfc.sf2.core.actions.ActionManager;
import com.sfc.sf2.core.actions.CustomAction;
import com.sfc.sf2.core.actions.NonCombinableAction;
import com.sfc.sf2.core.settings.SettingsManager;
import com.sfc.sf2.core.gui.AbstractMainEditor;
import com.sfc.sf2.core.gui.controls.Console;
import com.sfc.sf2.core.settings.ViewSettings;
import com.sfc.sf2.helpers.PathHelpers;
import com.sfc.sf2.helpers.RenderScaleHelpers;
import com.sfc.sf2.portrait.Portrait;
import com.sfc.sf2.portrait.PortraitManager;
import com.sfc.sf2.portrait.actions.PortraitActionData;
import com.sfc.sf2.portrait.models.PortraitDataTableModel;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.nio.file.Path;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.TableModelEvent;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author wiz
 */
public class PortraitMainEditor extends AbstractMainEditor {
    
    private final ViewSettings viewSettings = new ViewSettings(RenderScaleHelpers.RENDER_SCALE_4X);
    private final PortraitManager portraitManager = new PortraitManager();
    
    private PortraitDataTableModel eyeTable;
    private PortraitDataTableModel mouthTable;
    private int selectedEyesRow;
    private int selectedMouthsRow;
    private final javax.swing.JCheckBox jCheckBoxKeepMetadata = new javax.swing.JCheckBox("Don't reload eyes/mouth", true);
    
    public PortraitMainEditor() {
        super();
        SettingsManager.registerSettingsStore("view", viewSettings);
        initComponents();
        initCore(console1);
    }
    
    @Override
    protected void initEditor() {
        super.initEditor();
        
        portraitViewPanel1.setLayoutPanel(portraitLayoutPanel, viewSettings);
        
        eyeTable = (PortraitDataTableModel)tableEyes.getModel();
        mouthTable = (PortraitDataTableModel)tableMouth.getModel();
        tableEyes.addTableModelListener(this::eyesListDataChanged);
        tableMouth.addTableModelListener(this::mouthListDataChanged);
        tableEyes.addListSelectionListener(this::eyesListSelectionChanged);
        tableMouth.addListSelectionListener(this::mouthListSelectionChanged);
        portraitLayoutPanel.setEyesChangedListener(this::eyesListValueChanged);
        portraitLayoutPanel.SetMouthChangedListener(this::mouthListValueChanged);
        TableColumnModel columns = tableEyes.jTable.getColumnModel();
        columns.getColumn(0).setMaxWidth(40);
        columns = tableMouth.jTable.getColumnModel();
        columns.getColumn(0).setMaxWidth(40);
        jCheckBoxKeepMetadata.setToolTipText("When importing a PNG/GIF, keep the currently loaded eye and mouth tables instead of replacing them from a .meta file.");
        try {
            jButtonImportImage.getParent().add(jCheckBoxKeepMetadata);
        } catch (Exception ignored) {
            jButtonImportImage.setToolTipText(jCheckBoxKeepMetadata.getToolTipText() + " (checkbox could not be added to this layout)");
        }
    }
    
    @Override
    protected void onDataLoaded() {
        super.onDataLoaded();
        ActionManager.setAndExecuteAction(new NonCombinableAction<Portrait>(this, "Portrait Imported", this::actionPortraitLoaded, portraitManager.getPortrait(), portraitLayoutPanel.getPortrait()));
    }
    
    private void actionPortraitLoaded(Portrait portrait) {        
        portraitLayoutPanel.setPortrait(portrait);
        selectedEyesRow = selectedMouthsRow = -1;
        if (portrait == null) {
            eyeTable.setTableData(null);
            mouthTable.setTableData(null);
        } else {
            eyeTable.setTableData(portrait.getEyeTiles());
            mouthTable.setTableData(portrait.getMouthTiles());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        portraitDataModelEyes = new com.sfc.sf2.portrait.models.PortraitDataTableModel();
        portraitDataModelMouth = new com.sfc.sf2.portrait.models.PortraitDataTableModel();
        jPanel13 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel15 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        tableEyes = new com.sfc.sf2.core.gui.controls.Table();
        tableMouth = new com.sfc.sf2.core.gui.controls.Table();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        portraitLayoutPanel = new com.sfc.sf2.portrait.gui.PortraitLayoutPanel();
        portraitViewPanel1 = new com.sfc.sf2.portrait.gui.PortraitViewPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fileButtonImportPortrait = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonImportPortrait = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fileButtonImportImage = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonImportMeta = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonImportImage = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fileButtonExportPortrait = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonExportPortrait = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fileButtonExportImage = new com.sfc.sf2.core.gui.controls.FileButton();
        fileButtonExportMeta = new com.sfc.sf2.core.gui.controls.FileButton();
        jButtonExportImage = new javax.swing.JButton();
        console1 = new com.sfc.sf2.core.gui.controls.Console();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SF2PortraitManager");

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        jSplitPane2.setDividerLocation(400);
        jSplitPane2.setOneTouchExpandable(true);

        jPanel6.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanel6.setPreferredSize(new java.awt.Dimension(325, 200));

        tableEyes.setBorder(javax.swing.BorderFactory.createTitledBorder("Eyes"));
        tableEyes.setInfoMessage("<html>The \"animation\" of making the character blink.<br>- X/Y: The tile (8x8 pixels) on the portrait to replace.<br>- X'/Y': The tile outside of the portrait (right-side) that replaces at X/Y.<br><br>See the \"Blink frame\" toggle under the portrait.</html>");
        tableEyes.setModel(portraitDataModelEyes);
        tableEyes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableEyes.setSpinnerNumberEditor(true);
        tableEyes.setMinimumSize(new java.awt.Dimension(200, 200));
        tableEyes.setName("Eyes Table"); // NOI18N
        tableEyes.setPreferredSize(new java.awt.Dimension(350, 250));

        tableMouth.setBorder(javax.swing.BorderFactory.createTitledBorder("Mouth"));
        tableMouth.setInfoMessage("<html>The \"animation\" of making the character talk.<br>- X/Y: The tile (8x8 pixels) on the portrait to replace.<br>- X'/Y': The tile outside of the portrait (right-side) that replaces at X/Y.<br><br>See the \"Talk frame\" toggle under the portrait.</html>");
        tableMouth.setModel(portraitDataModelMouth);
        tableMouth.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableMouth.setSpinnerNumberEditor(true);
        tableMouth.setMinimumSize(new java.awt.Dimension(200, 200));
        tableMouth.setName("Mouth Table"); // NOI18N
        tableMouth.setPreferredSize(new java.awt.Dimension(350, 250));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableEyes, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
            .addComponent(tableMouth, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(tableEyes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableMouth, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Portrait"));

        jScrollPane2.setMinimumSize(new java.awt.Dimension(280, 180));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(280, 280));

        portraitLayoutPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        portraitLayoutPanel.setPreferredSize(new java.awt.Dimension(270, 270));

        javax.swing.GroupLayout portraitLayoutPanelLayout = new javax.swing.GroupLayout(portraitLayoutPanel);
        portraitLayoutPanel.setLayout(portraitLayoutPanelLayout);
        portraitLayoutPanelLayout.setHorizontalGroup(
            portraitLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        portraitLayoutPanelLayout.setVerticalGroup(
            portraitLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(portraitLayoutPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portraitViewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portraitViewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)))
        );

        jSplitPane2.setRightComponent(jPanel10);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Import from :"));
        jPanel3.setPreferredSize(new java.awt.Dimension(590, 135));

        jLabel2.setText("Import portrait disassembly.");

        fileButtonImportPortrait.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonImportPortrait.setFilePath("./portrait00.bin");
        fileButtonImportPortrait.setInfoMessage("");
        fileButtonImportPortrait.setLabelText("Portrait file :");
        fileButtonImportPortrait.setName("Import Portrait"); // NOI18N

        jButtonImportPortrait.setText("Import");
        jButtonImportPortrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportPortraitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileButtonImportPortrait, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonImportPortrait)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportPortrait, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImportPortrait)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Disassembly", jPanel4);

        jLabel3.setText("Import portrait from image and meta.");

        fileButtonImportImage.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ANY_IMAGE);
        fileButtonImportImage.setFilePath("./export/portrait00.png");
        fileButtonImportImage.setInfoMessage("<html>Supported image formats: PNG or GIF.<br><br>Color format should be 4BPP / 16 indexed colors. Images of 8BPP / 256 indexed colors will be converted to 4 BPP / 16 (some colors may be lost).<br>When imported, icons will use the base palette colors.<br>Color index 0 is treated as transparent.</html>");
        fileButtonImportImage.setLabelText("Image file :");
        fileButtonImportImage.setName("Import Image"); // NOI18N

        fileButtonImportMeta.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.META);
        fileButtonImportMeta.setFilePath(".meta");
        fileButtonImportMeta.setInfoMessage("<html>Meta file stores the eye and mouth 'animation' data for the portrait.</html>");
        fileButtonImportMeta.setLabelText("Meta file :");
        fileButtonImportMeta.setName("Import Meta"); // NOI18N

        jButtonImportImage.setText("Import");
        jButtonImportImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonImportImage, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(fileButtonImportMeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonImportImage)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonImportMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImportImage)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Image", jPanel9);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Export to :"));
        jPanel5.setPreferredSize(new java.awt.Dimension(32, 135));

        jLabel1.setText("Export portrait disassembly.");

        fileButtonExportPortrait.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.BIN);
        fileButtonExportPortrait.setFilePath("./portrait00.bin");
        fileButtonExportPortrait.setInfoMessage("");
        fileButtonExportPortrait.setLabelText("Portrait file :");
        fileButtonExportPortrait.setName("Export Portrait"); // NOI18N

        jButtonExportPortrait.setText("Export");
        jButtonExportPortrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportPortraitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonExportPortrait, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonExportPortrait))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonExportPortrait, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExportPortrait)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Disassembly", jPanel11);

        jLabel9.setText("Export portrait as image.");

        fileButtonExportImage.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.ANY_IMAGE);
        fileButtonExportImage.setFilePath("./export/portrait00.png");
        fileButtonExportImage.setInfoMessage("<html>Supported image formats: PNG or GIF.<br><br>Exported color format will be 4BPP / 16 indexed colors.<br>Color index 0 is treated as transparent.</html>");
        fileButtonExportImage.setLabelText("Image file :");
        fileButtonExportImage.setName("Export Image"); // NOI18N

        fileButtonExportMeta.setFileFormatFilter(com.sfc.sf2.core.io.FileFormat.META);
        fileButtonExportMeta.setFilePath(".meta");
        fileButtonExportMeta.setInfoMessage("<html>Meta file stores the eye and mouth 'animation' data for the portrait.</html>");
        fileButtonExportMeta.setLabelText("Meta file :");
        fileButtonExportMeta.setName("Export Meta"); // NOI18N

        jButtonExportImage.setText("Export");
        jButtonExportImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileButtonExportImage, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonExportImage))
                    .addComponent(fileButtonExportMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonExportImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButtonExportMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExportImage)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Image", jPanel14);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jSplitPane2.setLeftComponent(jPanel8);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        jSplitPane1.setTopComponent(jPanel15);
        jSplitPane1.setBottomComponent(console1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1096, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExportPortraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportPortraitActionPerformed
        Path portraitPath = PathHelpers.getBasePath().resolve(fileButtonExportPortrait.getFilePath());
        if (!PathHelpers.createPathIfRequred(portraitPath)) return;
        try {
            portraitManager.exportDisassembly(portraitPath, portraitLayoutPanel.getPortrait());
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Portrait disasm could not be exported to : " + portraitPath);
        }
    }//GEN-LAST:event_jButtonExportPortraitActionPerformed

    private void jButtonExportImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportImageActionPerformed
        Path imagePath = PathHelpers.getBasePath().resolve(fileButtonExportImage.getFilePath());
        Path metaPath = PathHelpers.replaceExtension(imagePath, fileButtonExportMeta.getFilePath());
        if (!PathHelpers.createPathIfRequred(imagePath)) return;
        if (!PathHelpers.createPathIfRequred(metaPath)) return;
        try {
            portraitManager.exportImage(imagePath, metaPath, portraitLayoutPanel.getPortrait());
        } catch (Exception ex) {
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Portrait image could not be exported to : " + imagePath);
        }
    }//GEN-LAST:event_jButtonExportImageActionPerformed

    private void jButtonImportImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportImageActionPerformed
        Path imagePath = PathHelpers.getBasePath().resolve(fileButtonImportImage.getFilePath());
        Path metaPath = PathHelpers.replaceExtension(imagePath, fileButtonImportMeta.getFilePath());
        Portrait existing = portraitLayoutPanel.getPortrait();
        int[][] keepEyes = null;
        int[][] keepMouth = null;
        if (jCheckBoxKeepMetadata.isSelected() && existing != null) {
            keepEyes = existing.getEyeTiles();
            keepMouth = existing.getMouthTiles();
        }
        try {
            portraitManager.importImage(imagePath, metaPath);
            Portrait imported = portraitManager.getPortrait();
            if (imported != null && keepEyes != null) {
                imported.setEyeTiles(keepEyes);
                imported.setMouthTiles(keepMouth);
            }
        } catch (Exception ex) {
            portraitManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Portrait image or meta could not be imported from : " + imagePath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportImageActionPerformed

    private void jButtonImportPortraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportPortraitActionPerformed
        Path portraitPath = PathHelpers.getBasePath().resolve(fileButtonImportPortrait.getFilePath());
        try {
            portraitManager.importDisassembly(portraitPath);
        } catch (Exception ex) {
            portraitManager.clearData();
            Console.logger().log(Level.SEVERE, null, ex);
            Console.logger().severe("ERROR Portrait disasm could not be imported from : " + portraitPath);
        }
        onDataLoaded();
    }//GEN-LAST:event_jButtonImportPortraitActionPerformed
    
    private void eyesListDataChanged(TableModelEvent e) {
        if (e.getType() != TableModelEvent.DELETE && e.getType() != TableModelEvent.INSERT) return;
        Portrait portrait = portraitLayoutPanel.getPortrait();
        if (portrait == null) return;
        portrait.setEyeTiles(portraitDataModelEyes.getTableData(int[][].class));
        portraitLayoutPanel.redraw();
    }

    private void mouthListDataChanged(TableModelEvent e) {
        if (e.getType() != TableModelEvent.DELETE && e.getType() != TableModelEvent.INSERT) return;
        Portrait portrait = portraitLayoutPanel.getPortrait();
        if (portrait == null) return;
        portrait.setMouthTiles(portraitDataModelMouth.getTableData(int[][].class));
        portraitLayoutPanel.redraw();
    }
    
    private void eyesListSelectionChanged(ListSelectionEvent evt) {
        if (evt.getValueIsAdjusting() && selectedEyesRow == tableEyes.jTable.getSelectedRow()) return;
        selectedEyesRow = tableEyes.jTable.getSelectedRow();
        Portrait portrait = portraitLayoutPanel.getPortrait();
        if (portrait != null) {
            portraitLayoutPanel.setSelectedEyeTile(selectedEyesRow);
        }
    }
    
    private void mouthListSelectionChanged(ListSelectionEvent evt) {
        if (evt.getValueIsAdjusting() && selectedMouthsRow == tableMouth.jTable.getSelectedRow()) return;
        selectedMouthsRow = tableMouth.jTable.getSelectedRow();
        Portrait portrait = portraitLayoutPanel.getPortrait();
        if (portrait != null) {
            portraitLayoutPanel.setSelectedMouthTile(selectedMouthsRow);
        }
    }

    private void eyesListValueChanged(ActionEvent evt) {
        if (selectedEyesRow == -1 || selectedEyesRow != tableEyes.jTable.getSelectedRow()) return;
        if (!ActionManager.isActionTriggering()) {
            PortraitActionData newData = new PortraitActionData(tableEyes.jTable.getSelectedRow(), portraitLayoutPanel.getPortrait().getEyeTiles()[selectedEyesRow]);
            PortraitActionData oldData = new PortraitActionData(tableEyes.jTable.getSelectedRow(), eyeTable.getRow(selectedEyesRow));
            ActionManager.setActionWithoutExecute(new CustomAction<PortraitActionData>(tableEyes, "Eyes Changed", this::actionEyesListValueChanged, newData, oldData));
        }
        Portrait portrait = portraitLayoutPanel.getPortrait();
        if (portrait != null) {
            eyeTable.SetRow(selectedEyesRow, portrait.getEyeTiles()[selectedEyesRow]);
        }
    }
    
    private void actionEyesListValueChanged(PortraitActionData data) {
        int row = data.row();
        Portrait portrait = portraitLayoutPanel.getPortrait();
        if (portrait != null) {
            tableEyes.jTable.clearSelection();
            portrait.getEyeTiles()[row] = data.data();
            eyeTable.SetRow(selectedEyesRow, data.data());
            tableEyes.jTable.addRowSelectionInterval(row, row);
            portraitLayoutPanel.setSelectedEyeTile(row);
            selectedEyesRow = row;
        }
    }
    
    private void mouthListValueChanged(ActionEvent evt) {
        if (selectedMouthsRow == -1 || selectedMouthsRow != tableMouth.jTable.getSelectedRow()) return;
        if (!ActionManager.isActionTriggering()) {
            PortraitActionData newData = new PortraitActionData(tableMouth.jTable.getSelectedRow(), portraitLayoutPanel.getPortrait().getMouthTiles()[selectedMouthsRow]);
            PortraitActionData oldData = new PortraitActionData(tableMouth.jTable.getSelectedRow(), mouthTable.getRow(selectedMouthsRow));
            ActionManager.setActionWithoutExecute(new CustomAction<PortraitActionData>(tableMouth, "Mouths Changed", this::actionMouthsListValueChanged, newData, oldData));
        }
        Portrait portrait = portraitLayoutPanel.getPortrait();
        if (portrait != null) {
            mouthTable.SetRow(selectedMouthsRow, portrait.getMouthTiles()[selectedMouthsRow]);
        }
    }
    
    private void actionMouthsListValueChanged(PortraitActionData data) {
        int row = data.row();
        Portrait portrait = portraitLayoutPanel.getPortrait();
        if (portrait != null) {
            tableMouth.jTable.clearSelection();
            portrait.getMouthTiles()[row] = data.data();
            mouthTable.SetRow(selectedMouthsRow, data.data());
            tableMouth.jTable.addRowSelectionInterval(row, row);
            portraitLayoutPanel.setSelectedMouthTile(row);
            selectedMouthsRow = row;
        }
    }
    
    /**
     * To create a new Main Editor, copy the below code
     * Don't forget to change the new main class (below)
     */
    public static void main(String args[]) {
        AbstractMainEditor.programSetup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PortraitMainEditor().setVisible(true);  // <------ Change this class to new Main Editor class
            }
        });
    }
    /**
     * To create a new Main Editor, copy the above code
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sfc.sf2.core.gui.controls.Console console1;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportImage;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportMeta;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonExportPortrait;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportImage;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportMeta;
    private com.sfc.sf2.core.gui.controls.FileButton fileButtonImportPortrait;
    private javax.swing.JButton jButtonExportImage;
    private javax.swing.JButton jButtonExportPortrait;
    private javax.swing.JButton jButtonImportImage;
    private javax.swing.JButton jButtonImportPortrait;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.sfc.sf2.portrait.models.PortraitDataTableModel portraitDataModelEyes;
    private com.sfc.sf2.portrait.models.PortraitDataTableModel portraitDataModelMouth;
    private com.sfc.sf2.portrait.gui.PortraitLayoutPanel portraitLayoutPanel;
    private com.sfc.sf2.portrait.gui.PortraitViewPanel portraitViewPanel1;
    private com.sfc.sf2.core.gui.controls.Table tableEyes;
    private com.sfc.sf2.core.gui.controls.Table tableMouth;
    // End of variables declaration//GEN-END:variables
}
