version: 1.4.4
release-notes:
v1.4.4: Checkbox cells only toggle when the box itself is clicked (#42).
v1.4.3: Linux platform support.
v1.4.1: Fixed issues when adding new frames to animations. Adding new frames are editable again.
v1.4.0: Added undo/redo feature. Added settings for all view options. Added individual buttons to import bg/ground and weapon (to no longer reset animation data).
v1.3.4: Added help menu with discord and GitHub links. More (?) buttons for info.
v1.3.3: Fixed when frames are reordered.
v1.3.2: Fixed battlesprite frame column.
v1.3.1: Up/down arrow buttons for number editing in table. Fixes to battleSprite not updating for edited row.
v1.3.0: New style. CRAM Color. Small changes to simplify interface + info buttons.