version: 1.3.3
release-notes:
v1.3.3: Unused-block overlay for maps (#45).
v1.3.2: Linux platform support.
v1.3.0: Added undo/redo feature. Added settings for all view options.
v1.2.1: Added help menu with discord and GitHub links. More (?) buttons for info.
v1.2.0: Updated to new style and CRAM colors. Better user interaction with blocks/tiles. Better add/clone/remove buttons.