version: 9.9.9-forktest
release-notes:
v9.9.9-forktest: Dummy bump to dry-run the split CI pipeline on tylerphotos forks.
v1.6.3: Linux platform support.
v1.6.1: Palette colors can be reordered.
v1.6.0: Added undo/redo feature. Added settings for all view options.
v1.5.5: Added help menu with discord and GitHub links. More (?) buttons for info.
v1.5.4: Smoother input for selecting palette items.
v1.5.3: Force all (disasm) colors to be CRAM colors.
v1.5.2: Small bug fix for null errors. Added info on CRAM color.
