version: 1.8.4
release-notes:
v1.8.4: Per-tile AI-region detection overlay (#35).
v1.8.3: Linux platform support.
v1.8.1: Display battle names before importing. Show warning with too many mapsprites in battle. Fixed errors when creating new enemy entry.
v1.8.0: Added undo/redo feature. Added settings for all view options. Small fixes to enemy item and item flag fields.
v1.7.3: Added help menu with discord and GitHub links. More (?) buttons for info.
v1.7.2: Alert to inform if terrain is used across multiple battles.
v1.7.1: Included editing land effect.
v1.7.0: Updated to new style. Improved editing and visualisation for coords, terrain and spritesets.