version: 1.9.5
release-notes:
v1.9.5: Fix roof-flag visuals (#61), map animation save (#59), mapsetup entity overlay (#36), unused block overlay (#45), smaller window (#46).
v1.9.4: Linux platform support.
v1.9.2: Fixes and info for map animation panel.
v1.9.1: Fixes to removing map flags. Showing map name before loading map.
v1.9.0: Added undo/redo feature. Added settings for all view options. Small bug fixes.
v1.8.4: Added the missing Step flag.
v1.8.3: Added help menu with discord and GitHub links. More (?) buttons for info.
v1.8.2: Fixes and improvements from v1.8.1. Fixes to adding/cloning/removing blocks.
v1.8.1: Fixes from v1.8.0 release.
v1.8.0: Updated to new style. Incorporated animation and block editing. Many new visualisations and features.